package_assets:         on
embed_assets:           on
javascript_compressor:  closure

#javascripts:
#  workspace:
#    - public/javascripts/vendor/*.js
#    - public/javascripts/application.js
#    - public/javascripts/lib/bindable.js
#    - public/javascripts/lib/set.js
#    - public/javascripts/lib/*.js
#    - public/javascripts/**/*.js
#    - app/views/workspace/*.jst

stylesheets:
  common:
    - public/stylesheets/library.css
